### ISSUE TITLE
c++ version

### ISSUE THREAD

**Issue by rootkit** [aobo-y/hair-dye#2]
Are you ready to support c++ version source code?

**Comment by aobo-y** [comment]
I am not sure if I understand you correctly. Do you mean you want to rewrite the project in c++? Or you are asking if we have the plan to rewrite it in c++?

**Comment by rootkit** [comment]
Yes, rewriting c++, so we can run on mobile OS just like iphone or android, user can take a photo to dye hair. that would be great!

**Comment by rootkit** [comment]
Maybe mobile OS does not work for low memory or cpu....

**Comment by aobo-y** [comment]
Sounds interesting. However, we do not have any short plans to rewrite it in C++, although pytorch has a C++ frontend.
Currently, we are still focusing on improving the current model and dying algorithm.
You may want to look for some other solutions like compiling python to native code.
